# Site settings
name: tony
email: tony@kyf.ai
author: tonyyp
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/dsahkl
baseurl: ''
description: 好好学习，天天向上
meta_description: tony;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 好好学习，天天向上
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: dsahkl

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

